### PR TITLE
Test hook for running data pipeline through API connection

### PR DESCRIPTION
**Pull request by blpham**
Unit test to ensure DataPipelineHook is calling Google Data Pipelines API to run test data pipeline.

### CODE REVIEW

**Review by shaniyaclement — COMMENTED** [review]
On line 66, I noticed that it is pulling from an actual connection id. Change to be a mock connection id to ensure it is passing when mocked? Also, maybe set line 76 to a variable and check that it is returning the same as what the mock_request is set to in line 74. Besides that I think it looks nice

**Comment by blpham** [comment]
> On line 66, I noticed that it is pulling from an actual connection id. Change to be a mock connection id to ensure it is passing when mocked? Also, maybe set line 76 to a variable and check that it is returning the same as what the mock_request is set to in line 74. Besides that I think it looks nice

icic makes sense, i'll update in a moment!

**Review by xianhualiu — COMMENTED** [review]
LGTM

**Comment by Dippatel98** [comment]
LGTM

**Review by shaniyaclement — APPROVED** [review]
nice update! Dip shared that using the actual conn id is fine because Dataflow tests used it so no worries

**Pull request merged**
